config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :settings, :only => [:new, :edit, :create, :update]
  resources :test_settings , only: [] do
    collection do
      post :send_email
      get :new_email
    end
  end

  root 'settings#new'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  after_create :clear_message
  
  private
  
  def clear_message
    Rails.cache.delete("messages_#{self.user.try(:id)}")
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates :email, email_format: { message: "doesn't look like an email address" }
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :setting
  has_many :messages

  def can_send_notification?
    setting.try(:enable_notification) && setting.try(:email).present?
  end

  def get_all_messages
    Rails.cache.fetch("messages_#{self.id}") do
      self.messages
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :authenticate_user!

  # should redirect to edit setting if global setting already exist.
  def new
    unless current_user.setting.present?
      @setting = Setting.new
    else
      redirect_to edit_setting_path(current_user.setting)
    end
  end

  # should redirect to new setting if current user does not have global setting.
  def edit
    @setting = current_user.setting
    redirect_to new_setting_path unless @setting.present?
  end

  def create
    @setting = current_user.build_setting(setting_param)
    if @setting.save
      redirect_to edit_setting_path(@setting), notice: 'Setting saved successfully.'
    else
      render action: :new
    end
  end

  def update
    @setting = current_user.setting
    if @setting.update(setting_param)
      redirect_to edit_setting_path(@setting), notice: 'Setting updated successfully.'
    else
      render action: :edit
    end
  end

  private

  def setting_param
    params.require(:setting).permit( :email, :enable_notification )
  end

end

app/controllers/test_settings_controller.rb
class TestSettingsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :can_send_message

  # This action is used to chek the global setting. if notification is enabled and the email is is given,
  # Then the email should be sent.
  def send_email
    unless params[:message].blank?
      Message.create(:user_id => current_user.id, :body => params[:message])
      Notifier.test_message(current_user.setting.try(:email), params[:message]).deliver
      flash[:notice] = "Message sent successfully."   
    else
      flash[:notice] = "Please insert the message"
    end
    redirect_to new_email_test_settings_path
  end

  def new_email
  end

  private

  # This filter redirect to global setting page, if setting is not proper.
  def can_send_message
    unless current_user.can_send_notification?
      redirect_to new_setting_path, :notice => "you need to set email and enable notification to test global setting."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/test_settings_helper.rb
module TestSettingsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3><%= link_to 'Global Setting Demo', root_path%></h3>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills">
        <% if user_signed_in? %>
          <li><%= link_to "Global-Setting", new_setting_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path  %></li>
          <li><%= link_to "Login", new_user_session_path  %></li>
        <% end %>
      </ul>  
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlobalSetting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>
  <br/>
  <br/>
  <%= yield %>

</body>
</html>

app/views/notifier/message.html.erb
<%= @message %>

app/views/notifier/test_message.html.erb
<%= @message %>

app/views/settings/_form.html.erb
<div class="container">
  <div class="row">
    <div class="panel-body col-md-6">
      <%= form_for @setting, :html => { :class => "form-horizontal setting" } do |f| %>
        <% if @setting.errors.any? %>
          <div>
            <% @setting.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :email, :class => 'control-label' %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.check_box :enable_notification %>
          <%= f.label :enable_notification %>
        </div>
        <div class="form-group">
          <%= f.submit nil, :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to "Test Global Setting Email", new_email_test_settings_path %>
  <br>
  Note: To test the global setting, please click on the link above.
</div>

app/views/settings/edit.html.erb
<%= render :partial => 'form' %>

app/views/settings/new.html.erb
<%= render :partial => 'form' %>

app/views/test_settings/new_email.html.erb
<div class="container">
  <div class="row">
    <div class="panel-body col-md-6">
      <%= form_tag send_email_test_settings_path, :html => { :class => "form-horizontal setting" } do %>
        <div class="form-group">
          <%= label_tag :email, "Message" %>
          <%= text_area_tag :message, nil,:placeholder => 'Message', class: "form-control"%>
        </div>
        <div class="form-group">
          <%= submit_tag 'Send Email', :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
    Note: This message would sent to <%= current_user.setting.try(:email) %>
  </div>
  <div class="row">
    <div class="panel-body col-md-6">
      <% current_user.get_all_messages.each do |msg| %>
        <%= msg.created_at %><br/>
        <%= msg.body %><br><br>
      <% end %>
    </div>
  </div>
</div>